### ISSUE TITLE
Invalid hour value for cron job

### ISSUE THREAD

**Issue by taterbase** [djmrr/maintainer#1]
The hour value you specify for the cron job is not a valid value. Go back and check the docs for cron jobs, I think you'll see where your mistake is.

https://en.wikipedia.org/wiki/Cron#Configuration_file
https://github.com/djmrr/maintainer/blob/master/scripts/maintainerHandoff.js#L6

**Comment by djmrr** [comment]
Hahah, I see, fixed - pushing changes
